### ISSUE TITLE
Adding freud tests to my project

### ISSUE THREAD

**Issue by chrisvest** [LMAX-Exchange/freud#6]
It looks like there's no release in maven central. Probably because there hasn't been any releases of freud? Is there a snapshot repo I can use in the mean time, or is building locally the only way at present?

**Comment by langera** [comment]
Hi Chris,

Building locally is the only way at present and I'm not sure it'll change.
Freud has not been active for some time now.

Amir

**Comment by mikeb01** [comment]
We don't use Freud anymore and focus our custom static analysis effort on Findbugs and Intellij custom inspections.

I wouldn't invest any time using Freud and we will be discontinuing it soon.
